// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-ctYLvyLE7rgK-xz5Y2P3Sihz_9OEjOg',
    appId: '1:1036262784460:web:dc714b73f44bd9b44af169',
    messagingSenderId: '1036262784460',
    projectId: 'flutter-notification-buzzcu',
    authDomain: 'flutter-notification-buzzcu.firebaseapp.com',
    storageBucket: 'flutter-notification-buzzcu.appspot.com',
    measurementId: 'G-M156X9RDSW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiSjBvPJu20nSCWicBbgCPxkiYxAdaRRA',
    appId: '1:1036262784460:android:cff9d5b9f1270aeb4af169',
    messagingSenderId: '1036262784460',
    projectId: 'flutter-notification-buzzcu',
    storageBucket: 'flutter-notification-buzzcu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6YHdDXe1_SIsoJR7hgNy8IV6dj42sjoQ',
    appId: '1:1036262784460:ios:ea8cd03c77e03e894af169',
    messagingSenderId: '1036262784460',
    projectId: 'flutter-notification-buzzcu',
    storageBucket: 'flutter-notification-buzzcu.appspot.com',
    iosClientId: '1036262784460-vo76lbeffbmltkjhlc8s87g8l0p5jkbd.apps.googleusercontent.com',
    iosBundleId: 'com.example.cubuzz',
  );
}
